# Generated by Django 6.1 on 2026-08-28 18:39

import django.db.models.deletion
import infraestructura.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodoservidor',
            name='direccion_ip',
            field=models.GenericIPAddressField(validators=[infraestructura.models.validate_ip], verbose_name='Dirección IP'),
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(verbose_name='Detalle del Evento')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='infraestructura.nodoservidor')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
            },
        ),
    ]
