# Generated by Django 6.1 on 2026-09-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0002_alter_nodoservidor_direccion_ip_registroauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título de incidencia')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de incidencia')),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10, verbose_name='Severidad')),
                ('estado_res', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], max_length=10, verbose_name='Estado de Resolución')),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='infraestructura.nodoservidor')),
            ],
            options={
                'verbose_name': 'Incidencia de Servidor',
                'verbose_name_plural': 'Incidencias de Servidor',
            },
        ),
    ]
